version: "3.9"

services:

  ai-balancer:
    build: .
    container_name: ai-balancer-test
    environment:
      - AI_BALANCER_SERVER_BIND_ADDR=:9080
    depends_on:
      - chat-model
      - image-model
      - audio-model
    ports:
      - "9080:9080"

  chat-model:
    image: hashicorp/http-echo
    command: ["-text={\"response\":\"chat-response\"}"]
    ports:
      - "8081:5678"

  image-model:
    image: hashicorp/http-echo
    command: ["-text={\"url\":\"image-url\"}"]
    ports:
      - "8082:5678"

  audio-model:
    image: hashicorp/http-echo
    command: ["-text={\"url\":\"audio-url\"}"]
    ports:
      - "8083:5678"

  tests:
    image: golang:1.26
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - ai-balancer
    command: >
      sh -c "
      sleep 5 &&
      go test ./internal/app/api -v
      "