[server]
bind_addr = ":9080"

[logger]
level = "debug"

[jaeger]
url = "http://jaeger:14268/api/traces"

[models.chat]
endpoint = "http://balancerai-chat-model-1:5678/generate"
api_key = "test-key"

[models.image]
endpoint = "http://image-model:8080/generate"
api_key = "test-key"

[models.audio]
endpoint = "http://audio-model:8080/generate"
api_key = "test-key"